### ISSUE TITLE
Distribute ArchWSL through the `choco` package manager

### ISSUE THREAD

**Issue by Jarmos-san** [yuk7/ArchWSL#277] opened 2022-03-27 09:52 UTC
**Describe the issue**
I'm aware ArchWSL is distributed through `scoop` but is it possible to distribute ArchWSL through [Chocolatey](https://chocolatey.org/)? I don't mind sharing a helping hand to package it for distribution through `choco`.

**Comment by Smart123s** [comment] 2022-03-29 07:59
Duplicate of https://github.com/yuk7/ArchWSL/issues/104

**Closed** 2022-03-29 09:07 UTC
