### ISSUE TITLE
The file path is on on \\wsl$ 

### ISSUE THREAD

**Issue by rromanv** [yuk7/ArchWSL#172] opened 2020-12-10 22:22 UTC
**Describe the issue**
The file path is on on \\wsl$ as it is in other linux distros

**To Reproduce**
Open Run (Windows Key + R) and type \\wsl$

That will sned you to all the file systems of the wsl distros, Arch is not there

**Expected behavior**
To be able to see Arch filesystem from there

**Screenshots**
![explorer_5fGM13PBbf](https://user-images.githubusercontent.com/7709980/101836573-44ca9580-3b03-11eb-94b8-1bd54f6abcbf.png)

**Enviroment:**
 - Windows build number: 10.0.18363.1198
 - Security Software: NA
 - WSL version 1/2: 2

**Comment by escape0707** [comment] 2020-12-11 16:39
Works for me...

![image](https://user-images.githubusercontent.com/11014745/101929941-71210780-3c12-11eb-87da-b57638fdbfb9.png)

**Comment by nisarg-ujjainkar** [comment] 2021-02-09 15:45
It appears there only in wsl2. You probably might be using wsl1

**Comment by rffontenelle** [comment] 2022-05-22 02:13
@rromanv Do you still have this issue? If not, consider closing this issue. I can't reproduce it myself in my Windows 11 (build number 10.0.22000), WSL 2, ArchWSL 22.3.18.0.

**Closed** 2022-07-22 01:16 UTC
Labels: windows田
