### ISSUE TITLE
Dynamic library issue

### ISSUE THREAD

**Issue by juergenpf** [yuk7/ArchWSL#5] opened 2017-12-20 20:37 UTC
When I install texmaker (pacman -S texmaker) - which uses Qt5 - when starting it I get an error message that the dynamic loader couldn't find libQ5Core.so.5 (I've started Xming as an X-Server and set DISPLAY accordingly).
Looking at the ldconfig listing the library is shown and it is in the expected location in the file system.
This works without problem with Ubuntu/WSL

**Comment by yuk7** [comment] 2017-12-21 05:03
@juergenpf 
I confirmed the problem. 
This problem is probably due to the absence of renameat2 system call in WSL.
latest Qt 5.10 is using renameat2,You need to downgrade qt5-base.

**Comment by yuk7** [comment] 2017-12-21 05:42
@juergenpf 
Downgrade qt5-base and qt5-script to 5.9.x,you can probably solve it.
```bash
wget https://archive.archlinux.org/packages/q/qt5-base/qt5-base-5.9.3-1-x86_64.pkg.tar.xz
wget https://archive.archlinux.org/packages/q/qt5-script/qt5-script-5.9.3-1-x86_64.pkg.tar.xz
pacman -U qt5-base-5.9.3-1-x86_64.pkg.tar.xz qt5-script-5.9.3-1-x86_64.pkg.tar.xz
```

**Comment by yuk7** [comment] 2017-12-31 12:19
I'll close this issue.
This problem is due to WSL.

**Closed by yuk7** 2017-12-31 12:19 UTC
